doctrine:
    dbal:
        driver: postgresql
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Ads:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Core\Ads\Domain'